default_language_version:
  python: python3.12

# Only commit is installed by default: https://pre-commit.com/#pre-commit-install
# Pending rename of pre-push from: https://github.com/pre-commit/pre-commit/issues/2732
default_install_hook_types: ["commit-msg", "pre-commit"]

repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
        types: [text]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        types: [text]
      - id: mixed-line-ending
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: [--remove]
      - id: debug-statements
        types: [python]

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.27.0
    hooks:
      - id: check-github-workflows
        types: [yaml]

  - repo: https://github.com/sirosen/texthooks
    rev: 0.5.0
    hooks:
      - id: fix-smartquotes

  - repo: https://github.com/pappasam/toml-sort
    rev: "v0.23.1"
    hooks:
      - id: toml-sort
        args: [--in-place]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        types_or: [html, javascript, shell, yaml, json]

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        types: [python]
        args: [--in-place, --wrap-summaries=99, --wrap-descriptions=99]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.6.2"
    hooks:
      - id: ruff
        name: ruff linter
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        types_or: [python, pyi, jupyter]
