[tasks.format]
description = "Format/lint all files in one go"
run = "uv run pre-commit run -a"

[tasks.release]
description = "Release a new version"
run = "uv run cz bump --changelog --tag --yes"

[tasks.tests]
description = "Run all tests"
run = "uv run pytest"

[tools]
python = "3.10"
uv = "latest"
