name: CI

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  DEFAULT_PYTHON_VERSION: "3.12"
  CI: "1"

jobs:
  changes:
    name: Check for Python file changes
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    outputs:
      python: ${{steps.filter.outputs.python}}
      pre_commit_config: ${{steps.filter.outputs.pre_commit_config}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            python:
              - '**/*.py'
              - 'storage/fixtures/**/*'
              - 'configs/**/*'
              - 'pyproject.toml'
              - 'pdm.lock'
              - '.github/workflows/ci.yaml'
            pre_commit_config:
              - '.pre-commit-config.yaml'

  check_pre_commit:
    runs-on: ubuntu-latest
    needs: [changes]
    if: ${{ (needs.changes.outputs.python == 'true' || needs.changes.outputs.pre_commit_config == 'true') && !github.event.pull_request.draft }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.DEFAULT_PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
          cache: "pip"

      - name: Install pre-commit
        run: |
          pip install pre-commit

      - name: Load cached pre-commit environment
        uses: actions/cache@v4
        id: pre-commit-cache
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-

      - name: Run pre-commit hook
        id: run-pre-commit-hooks
        run: |
          git add .pre-commit-config.yaml
          pre-commit run --color=always --all-files

      - name: Annotate any changes using reviewdog
        if: ${{ failure() }}
        id: reviewdog-suggester
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: pre-commit

  based_pyright:
    runs-on: ubuntu-latest
    needs: [changes]
    if: ${{needs.changes.outputs.python == 'true' && !github.event.pull_request.draft }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
          cache: true

      - name: Install dependencies
        run: pdm install

      - name: Run basedpyright
        run: pdm run basedpyright

  test:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    runs-on: ubuntu-latest
    needs: [changes]
    if: ${{needs.changes.outputs.python == 'true' && !github.event.pull_request.draft }}
    steps:
      - name: Checkpout repository
        uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true

      - name: Install dependencies
        run: pdm install --without lint

      - name: Run tests
        run: pdm run pytest -n 2
